GET http://localhost:8080 HTTP/1.1
###
GET https://spring2023.onrender.com HTTP/1.1


// Local
###
GET http://localhost:8080/contact HTTP/1.1

### 
GET http://localhost:8080/contact/6456eb13f190430926f4e4f3 HTTP/1.1

###
POST http://localhost:8080/contact HTTP/1.1
content-type: application/json

{
    "firstName":"urmum", 
    "lastName":"Johnson", 
    "email":"tristan.johnson@test.com", 
    "favoriteColor":"Maroon", 
    "birthday":"05/06/2023"
}

### 
PUT http://localhost:8080/contact/6456eb13f190430926f4e4f3 HTTP/1.1
content-type: application/json

{
    "firstName":"Tristan", 
    "lastName":"Johnson", 
    "email":"tristan.johnson@test.com", 
    "favoriteColor":"Purple", 
    "birthday":"01/01/2001"
}

###
DELETE http://localhost:8080/contact/6456eb13f190430926f4e4f3 HTTP/1.1

// Render
###
GET https://spring2023.onrender.com/contact HTTP/1.1

###
GET https://spring2023.onrender.com/contact/644d60cae3dad2be928a5d41 HTTP/1.1

###
POST https://spring2023.onrender.com/contact HTTP/1.1
content-type: application/json

{
    "firstName":"Tristan", 
    "lastName":"Johnson", 
    "email":"tristan.johnson@test.com", 
    "favoriteColor":"Maroon", 
    "birthday":"05/06/2023"
}

### 
PUT https://spring2023.onrender.com/contact/6456e96a5309ef355cc3e5b7 HTTP/1.1
content-type: application/json

{
    "firstName":"Tristan", 
    "lastName":"Johnson", 
    "email":"tristan.johnson@test.com", 
    "favoriteColor":"Purple", 
    "birthday":"01/01/2001"
}

###
DELETE https://spring2023.onrender.com/contact/6456f10e3943858534acf016 HTTP/1.1